#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
import graphql # require graphql-core pip package when generating python code

import logging
log = logging.getLogger(__name__)


def _ConfigureLogging(level=None):
    try:
        import mujincommon
        mujincommon.ConfigureRootLogger(level=level)
    except ImportError:
        logging.basicConfig(format='%(levelname)s %(name)s: %(funcName)s, %(message)s', level=logging.DEBUG)


def _ParseArguments():
    import argparse
    parser = argparse.ArgumentParser(description='Open a shell to use controllerclient')
    parser.add_argument('--loglevel', type=str, default=None, help='The python log level, e.g. DEBUG, VERBOSE, ERROR, INFO, WARNING, CRITICAL (default: %(default)s)')
    parser.add_argument('--url', type=str, default='http://localhost', help='URL of the controller (default: %(default)s)')
    parser.add_argument('--username', type=str, default='mujin', help='Username to login with (default: %(default)s)')
    parser.add_argument('--password', type=str, default='mujin', help='Password to login with (default: %(default)s)')
    return parser.parse_args()


def _FetchServerVersionAndSchema(url, username, password):
    from mujincontrollerclient.controllerclientraw import ControllerWebClient
    webClient = ControllerWebClient(url, username, password)
    response = webClient.Request('HEAD', '/api/v2')
    assert response.status_code == 200, 'Unable to fetch server version: %s' % response
    serverVersion = response.headers['Server'].split()[0]
    log.info('server version determined to be: %s', serverVersion)
    schema = graphql.build_client_schema(webClient.CallGraphAPI(graphql.get_introspection_query(descriptions=True), {}))
    return serverVersion, schema

def _DereferenceType(fieldType):
    while hasattr(fieldType, 'of_type'):
        fieldType = fieldType.of_type
    return fieldType

def _DiscoverQueryFields(fieldType):
    fieldType = _DereferenceType(fieldType)
    if not hasattr(fieldType, 'fields'):
        return None
    queryFields = {}
    for fieldName, field in fieldType.fields.items():
        queryFields[fieldName] = _DiscoverQueryFields(field.type)
    return queryFields

def _DiscoverMethods(queryOrMutationType):
    methods = []
    for operationName, field in queryOrMutationType.fields.items():
        methods.append({
            'operationName': operationName,
            'parameters': sorted([
                {
                    'parameterName': argumentName,
                    'parameterType': argument.type,
                    'parameterDescription': argument.description,
                    'parameterNullable': not isinstance(argument.type, graphql.GraphQLNonNull),
                }
                for argumentName, argument in field.args.items()
            ], key=lambda x: (x['parameterNullable'], x['parameterName'])),
            'description': field.description,
            'returnType': field.type,
            'queryFields': _DiscoverQueryFields(field.type),
        })
    return methods    

def _PrintMethod(queryOrMutation, operationName, parameters, description, returnType, queryFields):
    print('    def %s(self, %s):' % (operationName, ', '.join([
        '%s=None' % parameter['parameterName'] if parameter['parameterNullable'] else parameter['parameterName']
        for parameter in parameters
    ] + ['fields=None', 'timeout=None'])))
    if description:
        print('        """%s' % description)
        print('')
        print('        Args:')
        for parameter in parameters:
            print('            %s (%s): %s' % (parameter['parameterName'], parameter['parameterType'], parameter['parameterDescription']))
        print('            fields (list or dict): Optionally specify a subset of fields to return.')
        print('            timeout (float): Number of seconds to wait for response.')
        print('')
        print('        Returns:')
        print('            %s: %s' % (returnType, _DereferenceType(returnType).description))
        print('        """')
    print('        parameterNameTypeValues = [')
    for parameter in parameters:
        print('            (\'%s\', \'%s\', %s),' % (parameter['parameterName'], parameter['parameterType'], parameter['parameterName']))
    print('        ]')
    print('        queryFields = %r' % queryFields)
    print('        return self._CallSimpleGraphAPI(\'%s\', operationName=\'%s\', parameterNameTypeValues=parameterNameTypeValues, queryFields=queryFields, fields=fields, timeout=timeout)' % (queryOrMutation, operationName))

def _PrintClient(serverVersion, queryMethods, mutationMethods):
    print('# -*- coding: utf-8 -*-')
    print('#')
    print('# DO NOT EDIT, THIS FILE WAS AUTO-GENERATED')
    print('# GENERATED BY: %s' % os.path.basename(__file__))
    print('# GENERATED AGAINST: %s' % serverVersion)
    print('#')
    print('')
    print('from .controllergraphclientutils import ControllerGraphClientBase')
    print('')
    print('class ControllerGraphQueries:')
    print('')
    for queryMethod in queryMethods:
        _PrintMethod('query', **queryMethod)
        print('')
    print('')
    print('class ControllerGraphMutations:')
    print('')
    for mutationMethod in mutationMethods:
        _PrintMethod('mutation', **mutationMethod)
        print('')
    print('')
    print('class ControllerGraphClient(ControllerGraphClientBase, ControllerGraphQueries, ControllerGraphMutations):')
    print('    pass')
    print('')
    print('#')
    print('# DO NOT EDIT, THIS FILE WAS AUTO-GENERATED, SEE HEADER')
    print('#')
    print('')


def _Main():
    options = _ParseArguments()
    _ConfigureLogging(options.loglevel)

    serverVersion, schema = _FetchServerVersionAndSchema(options.url, options.username, options.password)
    queryMethods = _DiscoverMethods(schema.query_type)
    mutationMethods = _DiscoverMethods(schema.mutation_type)
    _PrintClient(serverVersion, queryMethods, mutationMethods)


if __name__ == "__main__":
    _Main()
